### ISSUE TITLE
Problemas en arranque cuando se usa el oscilador a XT (CIAA NXP y EDU CIAA NXP)

### ISSUE THREAD

**Issue by jcecconi** [ciaa/firmware_v2#35]
Descripción:
    Cuando la placa se pone a funcionar con el código de arranque de lpcopen, el mismo a veces es errático. Hay que resetearlo varias veces para que funcione porque parece quedarse colgada

Causa:
     Por un problema de HW, el cristal que se ha colocado es incorrecto.

Solución:
     Utilizandola en modo IRC (Internal RC) y dejandolo en ese modo funciona sin problemas, tal como loa hace lpcopen. Si se necesita usarlo a XT (para mnejo de USB por ejemplo) , es necesario recurrir a una demora adicional luego de habilitar el XT para permitir que el oscilador arranque y se estabilice. Esta demora adicional se hizo implemento dentro de la inicialización de la placa cuando se la llama aqui

https://github.com/ciaa/firmware_v2/blob/ef2628beaf0d51bb182364ae32a87df226af411e/modules/lpc11u68/base/src/sysinit.c#L58

aumentando el delay del valor original de 500 (lpcopen) a 5000 (ajustar en cada HW, colocar de más sólo demora unos mS el arranque inicial sin mayores inconvenientes aumentando la posibilidad de éxito)

https://github.com/ciaa/firmware_v2/blob/11b2dfeace1fc42db048e9ac3df091a29a63395b/modules/lpc4337_m4/board/src/board_sysinit.c#L138

Referencia: 
       Ver [issue de HW "Problemas en arranque cuando se usa el oscilador a XT (CIAA NXP y EDU CIAA NXP)"](https://github.com/ciaa/Hardware/issues/73), con explicación más detallada y oscilogramas

**Comment by epernia** [comment]
Ver en CIAA HW la solución.
